project:
  type: website

website:
  title: "Daniel Molitor"
  search: false
  site-url: https://dmolitor.com
  repo-url: https://github.com/dmolitor/dmolitor.github.io
  google-analytics: "UA-154890377-1"
  favicon: "media/_favicon.png"
  navbar:
    background: light
    title: "**Daniel Molitor**"
    search: false
    pinned: true
    collapse-below: md
    foreground: primary
    left: 
      - text: "**Research**"
        href: src/research/index.qmd
      - text: "**CV**"
        href: media/_cv.pdf
      - text: "**Scratchpad**"
        href: src/blog/index.qmd
    tools:
        - icon: github
          href: https://github.com/dmolitor
          text: Daniel's GitHub
        - icon: twitter-x
          href: https://x.com/danieljmolitor
          text: Daniel's Twitter
        - icon: envelope-fill
          href: mailto:molitdj97@gmail.com
          text: Daniel's Email
  page-footer:
    border: false
    background: light 
    center:
      - href: https://quarto.org/
        text: "Built with Quarto"

format:
  html:
    theme: 
      light: minty
    css: styles.css
    toc: true
    page-layout: full
