# .github/workflows/gh-pages.yml

name: Hugo deployment

on:
  push:
    branches:
      - main # change to the branch name for your project

jobs:
  build-deploy:
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
          # fetch-depth: 0
          
      - name: Hugo Deploy GitHub Pages
        uses: benmatselby/hugo-deploy-gh-pages@master
        env:
          HUGO_VERSION: 0.88.0
          TARGET_REPO: dmolitor/dmolitor.github.io
          TARGET_BRANCH: gh-pages
          TOKEN: ${{ secrets.HUGO_TOKEN }}
          CNAME: www.dmolitor.com

      #- name: Setup Hugo
      #  uses: benmatselby/hugo-deploy-gh-pages@master # peaceiris/actions-hugo@v2
      #  with:
      #    hugo_version: "latest"
      #    # hugo-version: "latest"

      #- name: Build
      #  run: hugo # --minify

      #- name: Deploy
      #  uses: peaceiris/actions-gh-pages@v3
      #  if: ${{ github.ref == 'refs/heads/main' }}
      #  with:
      #    github_token: ${{ secrets.GITHUB_TOKEN }}
      #    publish_branch: gh-pages
      #    publish_dir: ./public
